apiVersion: skaffold/v1beta4
kind: Config
# Enforce SKaffold to use Jib
build:
  local:
    push: false
# Generated artifact
  artifacts:
    - image: cvora/my-app
# Use jibMaven
#      jibMaven: {}
# Execute deployment.yml
deploy:
  kubectl:
    manifests:
      - kubernetes/deployment.yml
